name: Cairo CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out master branch
        uses: actions/checkout@v3
      - name: Step 2 - Getting scarb
        uses: software-mansion/setup-scarb@v1.3.2
      - name: Step 3 - Setting up snfoundry
        uses: foundry-rs/setup-snfoundry@v3
      - name: Step 4 - Running tests
        working-directory: ./packages/contracts
        run: scarb test
  
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check out master branch
        uses: actions/checkout@v3
      - name: Step 2 - Getting scarb
        uses: software-mansion/setup-scarb@v1.3.2
      - name: Step 3 - Checking format
        working-directory: ./packages/contracts
        run: scarb fmt --check
